version: "3.3"
services:
  postgres:
    image: postgres:12.15
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:root@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    links:
      - postgres
