# @host = http://0.0.0.0:8080
@host = http://0.0.0.0:9090
# @host = http://172.18.0.3:8080
@token = v2.local.yCpBlUOwstyAJnyJoog4odFKXbtvbGRIcUWvDK9-A1EthVltaQo6n24VGKR-dSgroLGA8oN2aLs_gbaRf_whcvFnxJ6yuvR_-WYpWEaHsk33qQnuMvBE-ckXbvo3ioho_TAutOunc8zzXSXqq6NgwX3_z129sKIQ7bxq1GhenwvtqUf_6Dzpqt2LabmxRKQWFNid188GlEgd7IYD_krLXXj75KI-BiBJaVZEWJMQNZ3CySqwA9Z7-jryNOyRUbmZcWSVXd-PCNPZiFS2IbU.bnVsbA


### user创建
POST {{host}}/users

{
   "username":"tianyu",
   "password":"123456",
   "full_name":"tianyu",
   "email" :"tianyu@gmail.com"
}

### user登陆
POST {{host}}/users/login

{
   "username":"tianyu",
   "password":"123456" 
}


### 转账
POST {{host}}/transfers

{
    "from_account_id":5,
    "to_account_id":1,
    "amount":200,
    "currency":"USD"
}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 


# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

### user登陆
POST {{host}}/tokens/renew_access

{
   "refresh_token":"v2.local.J9kKVdmyj0_3xc-PsDHCq-_oeiDf-hg_y2H3jIR-yzriO59bHus891SZkBf0lafuhTzQiri9gGWxz0XknSa63B2Dcd6HlvojlEHHajx6XLAjaMzjwErl8BYo1Z8ja2RoLQI0AV4GD9nOtHI2-5v7iKYUm0vfzYcuCL4gMwmokIRS47WosZ-t6I8fNNHXzMMiz34kLiVNJlAsEMlaegNH4CXPw4Qrfp9prHZS3NbdiPZ3aCRSGrWNZ1gmCy6E3ye080aSZIsvwEY4dqb_f74.bnVsbA"
}

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
### 创建用户
POST {{host}}/accounts
authorization:bearer {{token}}

{
    "owner":"tianyu",
    "currency":"USD"
}

### 获取用户
GET {{host}}/accounts/1
authorization:bearer {{token}}

### 获取用户列表
GET {{host}}/accounts?page_id=1&page_size=10
authorization:bearer {{token}}


 